// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroVestAPI.Models;

#nullable disable

namespace NeuroVestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528174237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeuroVestAPI.Models.AlertaSistema", b =>
                {
                    b.Property<Guid>("AlertaSistemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Criticidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlertaSistemaId");

                    b.HasIndex("LoginId");

                    b.HasIndex("PacienteId");

                    b.ToTable("alerta_sistema", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.AnaliseIAeRiscos", b =>
                {
                    b.Property<Guid>("AnaliseIAeRiscosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassificacaoTexto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RiscoCardiaco")
                        .HasColumnType("int");

                    b.Property<int>("RiscoCerebral")
                        .HasColumnType("int");

                    b.Property<int>("RiscoVascular")
                        .HasColumnType("int");

                    b.Property<int>("ScoreGeral")
                        .HasColumnType("int");

                    b.HasKey("AnaliseIAeRiscosId");

                    b.HasIndex("LoginId");

                    b.HasIndex("PacienteId");

                    b.ToTable("analise_ia_e_riscos", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.CondicaoPreExistente", b =>
                {
                    b.Property<Guid>("CondicaoPreExistenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCondicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CondicaoPreExistenteId");

                    b.HasIndex("LoginId");

                    b.HasIndex("PacienteId");

                    b.ToTable("condicao_pre_existente", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.Dispositivo", b =>
                {
                    b.Property<Guid>("DispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BateriaPorcentagem")
                        .HasColumnType("int");

                    b.Property<string>("CodigoHardware")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModoFuncionamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NomeDispositivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SinalPorcentagem")
                        .HasColumnType("int");

                    b.Property<string>("StatusOperacional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DispositivoId");

                    b.HasIndex("CodigoHardware")
                        .IsUnique();

                    b.HasIndex("LoginId");

                    b.ToTable("dispositivo", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.HistoricoManutencaoDispositivo", b =>
                {
                    b.Property<Guid>("HistoricoManutencaoDispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataManutencao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DispositivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoIntervencao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("HistoricoManutencaoDispositivoId");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("LoginId");

                    b.ToTable("historico_manutencao_dispositivo", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.LogExportacaoDados", b =>
                {
                    b.Property<Guid>("LogExportacaoDadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormatoArquivo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusOperacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LogExportacaoDadosId");

                    b.HasIndex("LoginId");

                    b.HasIndex("PacienteId");

                    b.ToTable("log_exportacao_dados", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.LogInteracaoIA", b =>
                {
                    b.Property<Guid>("LogInteracaoIAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContextoPacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraMensagem")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerguntaUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RespostaIa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokensConsumidos")
                        .HasColumnType("int");

                    b.HasKey("LogInteracaoIAId");

                    b.HasIndex("ContextoPacienteId");

                    b.HasIndex("LoginId");

                    b.ToTable("log_interacao_ia", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.Login", b =>
                {
                    b.Property<Guid>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LoginId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.MetricasOndasEEG", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Alpha")
                        .HasColumnType("int");

                    b.Property<int>("Beta")
                        .HasColumnType("int");

                    b.Property<int>("Delta")
                        .HasColumnType("int");

                    b.Property<int>("Gamma")
                        .HasColumnType("int");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SessaoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Theta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("SessaoId");

                    b.ToTable("metricas_ondas_eeg", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.ParametrizacaoAlerta", b =>
                {
                    b.Property<Guid>("ParametrizacaoAlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MensagemCustomizada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MetricaAlvo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorMaximoToleravel")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ValorMinimoToleravel")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ParametrizacaoAlertaId");

                    b.HasIndex("LoginId");

                    b.ToTable("parametrizacao_alerta", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.PerfilMedico", b =>
                {
                    b.Property<Guid>("PerfilMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PerfilMedicoId");

                    b.HasIndex("Crm")
                        .IsUnique();

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.ToTable("perfil_medico", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.PerfilPaciente", b =>
                {
                    b.Property<Guid>("PerfilPacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPaciente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<decimal>("Imc")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MedicoResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PerfilPacienteId");

                    b.HasIndex("CodigoPaciente")
                        .IsUnique();

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.HasIndex("MedicoResponsavelId");

                    b.ToTable("perfil_paciente", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.RecomendacaoSistema", b =>
                {
                    b.Property<Guid>("RecomendacaoSistemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnaliseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecomendacaoSistemaId");

                    b.HasIndex("AnaliseId");

                    b.HasIndex("LoginId");

                    b.ToTable("recomendacao_sistema", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.SessaoECGRawData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("FrequenciaAmostragemHz")
                        .HasColumnType("int");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SessaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("ValoresSinalMv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("SessaoId");

                    b.ToTable("sessao_ecg_raw_data", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.SessaoTelemetria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmplitudeEcg")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("FcBpm")
                        .HasColumnType("int");

                    b.Property<int>("FluxoCerebral")
                        .HasColumnType("int");

                    b.Property<decimal>("IndiceAlfaBeta")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OxigCerebralFnirs")
                        .HasColumnType("int");

                    b.Property<int>("PaDiastolica")
                        .HasColumnType("int");

                    b.Property<int>("PaSistolica")
                        .HasColumnType("int");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Spo2")
                        .HasColumnType("int");

                    b.Property<string>("StatusGeral")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VfcRmssd")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("PacienteId");

                    b.ToTable("sessao_telemetria", (string)null);
                });

            modelBuilder.Entity("NeuroVestAPI.Models.AlertaSistema", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.PerfilPaciente", "PerfilPaciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.AnaliseIAeRiscos", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.PerfilPaciente", "PerfilPaciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.CondicaoPreExistente", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.PerfilPaciente", "PerfilPaciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.Dispositivo", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.HistoricoManutencaoDispositivo", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Dispositivo", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.LogExportacaoDados", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.PerfilPaciente", "PerfilPaciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.LogInteracaoIA", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.PerfilPaciente", "PerfilPaciente")
                        .WithMany()
                        .HasForeignKey("ContextoPacienteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.MetricasOndasEEG", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.SessaoTelemetria", "SessaoTelemetria")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("SessaoTelemetria");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.ParametrizacaoAlerta", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.PerfilMedico", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithOne("PerfilMedico")
                        .HasForeignKey("NeuroVestAPI.Models.PerfilMedico", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.PerfilPaciente", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithOne("PerfilPaciente")
                        .HasForeignKey("NeuroVestAPI.Models.PerfilPaciente", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.PerfilMedico", "MedicoResponsavel")
                        .WithMany()
                        .HasForeignKey("MedicoResponsavelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Login");

                    b.Navigation("MedicoResponsavel");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.RecomendacaoSistema", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.AnaliseIAeRiscos", "AnaliseIAeRiscos")
                        .WithMany()
                        .HasForeignKey("AnaliseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaliseIAeRiscos");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.SessaoECGRawData", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.SessaoTelemetria", "SessaoTelemetria")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("SessaoTelemetria");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.SessaoTelemetria", b =>
                {
                    b.HasOne("NeuroVestAPI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroVestAPI.Models.PerfilPaciente", "PerfilPaciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("NeuroVestAPI.Models.Login", b =>
                {
                    b.Navigation("PerfilMedico");

                    b.Navigation("PerfilPaciente");
                });
#pragma warning restore 612, 618
        }
    }
}
